[package]
name = "duwop"
version = "0.1.0"
authors = ["Haim Ashkenazi <haim@babysnakes.org>"]
edition = "2018"

[dependencies]
trust-dns = { version = "0.15.1", default-features = false }
trust-dns-server = "0.15.1"
trust-dns-proto = "0.6.3"

tokio-udp = "0.1.3"
tokio = "0.1.18"
futures = "0.1.26"

log = "0.4.6"
env_logger = "0.6.1"