[package]
name = "duwop"
version = "0.7.0-dev"
authors = ["Haim Ashkenazi <haim@babysnakes.org>"]
edition = "2021"
license = "MIT"

[dependencies]
tokio = "1.18"
tokio-fs = "0.1"
tokio-io = "0.1"
futures = "0.1"
log = "0.4.6"
