[package]
name = "duwop"
version = "0.1.0"
authors = ["Haim Ashkenazi <haim@babysnakes.org>"]
edition = "2018"

[dependencies]
trust-dns-server = "0.15.1"
trust-dns = { version = "0.15.1", default-features = false }
tokio-udp = "0.1.3"
tokio = "0.1.18"
futures = "0.1.26"