name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Info
      run: rustup show
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
